Calendar
taka110-IT/ruby-practices pull request #2
Opened 2020-12-15 14:50 UTC by taka110-IT

カレンダーのプログラムの提出物を作成しました。

2020-12-20 08:55 UTC, u1tnk requested changes

2020-12-20 08:55 UTC, u1tnk commented on 01.fizzbuzz/fizzbuzz.rb
> +#!/usr/bin/env ruby
これはCalendarのPRなのでfizzbuzz問題の内容が出ないようにしてください。
別途mainに fizzbuzzのコミットをマージしまえばできますので。

2020-12-20 08:55 UTC, u1tnk commented on 02.calendar/cal.rb
> +if year_month_options["m"] != nil
これでも良いですが、ちょっと冗長ですね。
```
month = year_month_options["m"].to_i
month = Date.today.month if month == 0 # nil.to_i は0になるため
```

こっちの方が見やすいと思います。

2020-12-20 08:55 UTC, u1tnk commented on 02.calendar/cal.rb
> +    Date.new(year, month, x).wday.times do
細かいですが、
` print "    " *  Date.new(year, month, x).wday`
の方が見やすいかなと思いました。
文字列のかけ算ができるのは rubyの便利ポイントです  ✨

2020-12-20 08:55 UTC, u1tnk commented on 02.calendar/cal.rb
> +  if Date.new(year, month, x).wday == 6
今回はこれで良いですが、 2桁以下の数値を右詰めにするのは他のもっと簡単な方法でできるので調べておいてください。

2020-12-22 00:47 UTC, u1tnk commented on 02.calendar/cal.rb
> +  if Date.new(year, month, x).wday == 6
お。修正されましたね！
正解一つ出されたので、教えておくと [String#rjust (Ruby 2.7.0 リファレンスマニュアル)](https://docs.ruby-lang.org/ja/latest/method/String/i/rjust.html)  でもできます。
複数の変数を組み合わせるときは sprintf 、一つだけなら rjustと使い分けると良いと思います 💪

2020-12-22 00:48 UTC, u1tnk approved these changes

2020-12-22 13:57 UTC, taka110-IT reviewed
チェリー本を進めていたら出てきたので、こっちもあったか！とちょうど気付きました😅
ありがとうございました。

2020-12-22 13:57 UTC, merged